# Generated by Django 5.2.3 on 2025-07-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_production_truck_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='CylinderInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TruckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('truck_type', models.CharField(choices=[('loaded', 'Loaded'), ('unloaded', 'Unloaded')], max_length=10)),
                ('cylinder_count', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Production',
        ),
        migrations.DeleteModel(
            name='Truck',
        ),
    ]
