# Generated by Django 5.2.3 on 2025-07-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_cylinderinventory_trucklog_delete_production_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trucklog',
            name='cylinders_left',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trucklog',
            name='total_cylinders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trucklog',
            name='truck_identifier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trucklog',
            name='cylinder_count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='trucklog',
            name='truck_type',
            field=models.CharField(max_length=20),
        ),
    ]
